// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Cu_e1VtMn6InoQKctVDkQQGYVbMVz9g',
    appId: '1:994264266102:web:aedbdeb7fb1eee81aa7657',
    messagingSenderId: '994264266102',
    projectId: 'healthcare-app-6417',
    authDomain: 'healthcare-app-6417.firebaseapp.com',
    databaseURL: 'https://healthcare-app-6417-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-app-6417.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2QTOY1zvOmeJs6Lcj_YOFsPDnHKDIWk',
    appId: '1:994264266102:android:bda9e035fd2d8aeaaa7657',
    messagingSenderId: '994264266102',
    projectId: 'healthcare-app-6417',
    databaseURL: 'https://healthcare-app-6417-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-app-6417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJiMzLwohAlwLRCLygIGtya53EmqtWEZo',
    appId: '1:994264266102:ios:b3bc26ea423bcb56aa7657',
    messagingSenderId: '994264266102',
    projectId: 'healthcare-app-6417',
    databaseURL: 'https://healthcare-app-6417-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-app-6417.appspot.com',
    iosClientId:
        '994264266102-b3h4evb9tm15fv4m4lik3nbevjgjgohf.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJiMzLwohAlwLRCLygIGtya53EmqtWEZo',
    appId: '1:994264266102:ios:b3bc26ea423bcb56aa7657',
    messagingSenderId: '994264266102',
    projectId: 'healthcare-app-6417',
    databaseURL: 'https://healthcare-app-6417-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-app-6417.appspot.com',
    iosClientId:
        '994264266102-b3h4evb9tm15fv4m4lik3nbevjgjgohf.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Cu_e1VtMn6InoQKctVDkQQGYVbMVz9g',
    appId: '1:994264266102:web:da12b89bfaf1da01aa7657',
    messagingSenderId: '994264266102',
    projectId: 'healthcare-app-6417',
    authDomain: 'healthcare-app-6417.firebaseapp.com',
    databaseURL: 'https://healthcare-app-6417-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-app-6417.appspot.com',
  );
}
